# ImageValidatingPolicy: verify GitHub Artifact Attestation (SPDX SBOM).
# Aligned with Luc's testbed: https://github.com/lucchmielowski/kyverno-cosign-testbed
# No validationConfigurations; exact subject for refs/heads/main.
apiVersion: policies.kyverno.io/v1
kind: ImageValidatingPolicy
metadata:
  name: verify-github-sbom
  annotations:
    policies.kyverno.io/title: Verify GitHub SPDX SBOM attestation
    policies.kyverno.io/category: Software Supply Chain Security
    policies.kyverno.io/description: >-
      Enforces SPDX SBOM from GitHub Artifact Attestations (build-and-attest workflow).
spec:
  validationActions: [Deny]
  failurePolicy: Fail
  webhookConfiguration:
    timeoutSeconds: 30
  matchConstraints:
    resourceRules:
      - apiGroups: [""]
        apiVersions: ["v1"]
        operations: ["CREATE", "UPDATE"]
        resources: ["pods"]
  matchImageReferences:
    - glob: "ghcr.io/nirmata/*"
  attestations:
    - name: sbom
      intoto:
        type: "https://spdx.dev/Document/v2.3"
  attestors:
    - name: cosign
      cosign:
        keyless:
          identities:
            - subject: "https://github.com/nirmata/demo-supply-chain/.github/workflows/build-and-attest.yml@refs/heads/main"
              issuer: "https://token.actions.githubusercontent.com"
            - issuer: "https://token.actions.githubusercontent.com"
              subjectRegExp: "https://github\\.com/nirmata/demo-supply-chain/\\.github/workflows/build-and-attest\\.yml@refs/tags/v.*"
        ctlog:
          url: "https://rekor.sigstore.dev"
  validations:
    - expression: >-
        images.containers.map(image, verifyAttestationSignatures(image, attestations.sbom, [attestors.cosign])).all(e, e > 0)
      message: "Failed to verify SPDX SBOM attestation"
